{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc }}
{{- end }}
